[project]
name = "youqu-dogtail"
description = ""
authors = [
    { name = "mikigo", email = "huangmingqiang@uniontech.com" },
]
dependencies = [
    "funnylog",
]
dynamic = [
  "version",
]
requires-python = ">=3.7"
readme = "README.md"
license = { text = "GPL2.0" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.hatch]
version = { path = "youqu_dogtail/__version__.py" }

[tool.hatch.build.targets.wheel]
packages = [
    "/youqu_dogtail",
]

